services:

  app_1:
    build: .
    ports:
      - "3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=app_user
      - DATABASE_PASSWORD=app_password
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
  app_2:
    extends: app_1
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis:/data/redis
    command: redis-server
    ports:
      - '6379:6379'
    restart: unless-stopped
  ld_balancer:
    image: docker.io/nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app_1
      - app_2
volumes:
  postgres:
  redis:
